disabled_rules:
- line_length
- legacy_constructor
- empty_enum_arguments
- cyclomatic_complexity
- function_body_length
- large_tuple
- multiple_closures_with_trailing_closure
- force_try
- syntactic_sugar
- file_length
- identifier_name
- type_body_length
- trailing_whitespace
- force_cast
excluded:
- Pods
- Build
- DerivedData
